{{ if .Values.kubernetes.createNamespace }}
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "{{ .Values.helm.release }}"
    meta.helm.sh/release-namespace: "{{ .Values.helm.namespace }}"
  name: "{{.Values.kubernetes.namespace}}"
  labels:
    name: "{{.Values.kubernetes.namespace}}"
{{- end }}  