{{ if .Values.kubernetes.sap.createServiceAccount }}
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "{{ .Values.helm.release }}"
    meta.helm.sh/release-namespace: "{{ .Values.helm.namespace }}"  
    eks.amazonaws.com/role-arn: "{{ .Values.kubernetes.sap.roleArn }}"
  name: "{{ .Values.kubernetes.sap.serviceAccount }}"
  namespace: "{{.Values.kubernetes.namespace}}"
secrets:
- name: "{{ .Values.kubernetes.sap.serviceAccount }}-token"
{{- end }}  